doctrine:
    dbal:
        url: '%env(resolve:DATABASE_URL)%'
    orm:
        auto_generate_proxy_classes: true
        enable_lazy_ghost_objects: true
        naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
        report_fields_where_declared: true
        auto_mapping: true
        mappings:
            Auth:
                type: attribute
                is_bundle: false
                dir: '%kernel.project_dir%/src/Auth/Entity'
                prefix: 'App\Auth\Entity'
                alias: Auth
            Content:
                type: attribute
                is_bundle: false
                dir: '%kernel.project_dir%/src/Content/Entity'
                prefix: 'App\Content\Entity'
                alias: Content
            Video:
                type: attribute
                is_bundle: false
                dir: '%kernel.project_dir%/src/Video/Entity'
                prefix: 'App\Video\Entity'
                alias: Video
            Playlist:
                type: attribute
                is_bundle: false
                dir: '%kernel.project_dir%/src/Playlist/Entity'
                prefix: 'App\Playlist\Entity'
                alias: Playlist
            Tag:
                type: attribute
                is_bundle: false
                dir: '%kernel.project_dir%/src/Tag/Entity'
                prefix: 'App\Tag\Entity'
                alias: Tag

when@test:
    doctrine:
        dbal:
            dbname_suffix: '_test%env(default::TEST_TOKEN)%'

when@prod:
    doctrine:
        orm:
            auto_generate_proxy_classes: false
            proxy_dir: '%kernel.build_dir%/doctrine/orm/Proxies'
            query_cache_driver:
                type: pool
                pool: doctrine.system_cache_pool
            result_cache_driver:
                type: pool
                pool: doctrine.result_cache_pool

    framework:
        cache:
            pools:
                doctrine.result_cache_pool:
                    adapter: cache.app
                doctrine.system_cache_pool:
                    adapter: cache.system
