twig:
  form_themes:
    - '@FOSCKEditor/Form/ckeditor_widget.html.twig'
    - 'form/fields.html.twig'
  default_path: '%kernel.project_dir%/templates'
  globals:
    app_name: '%app.name%'

when@test:
  twig:
    strict_variables: true


