framework:
    workflows:
        feedback_status:
            type: 'state_machine'
            supports:
                - App\Domain\Feedback\Entity\Feedback
            marking_store:
                type: method
                property: status
            places:
                - new
                - read
                - resolved
                - processed
            transitions:
                mark_read:
                    from: new
                    to: read
                mark_processed:
                    from: read
                    to: processed
                mark_resolved:
                    from: read
                    to: resolved
