image: php:8.1-cli

stages:
  - deploy_new_vps

deploy_new_vps:
  stage: deploy_new_vps

  before_script:
    - apt-get update -yqq
    - apt-get install -yqq openssh-client
    - mkdir -p ~/.ssh
    - echo "$SSH_LAZAREFORTUNE_KEY" | base64 -d > ~/.ssh/id_deploy
    - chmod 600 ~/.ssh/id_deploy
    - ssh-keyscan -p "$SSH_LAZAREFORTUNE_PORT" -H "$SSH_LAZAREFORTUNE_HOST" >> ~/.ssh/known_hosts
    - chmod 644 ~/.ssh/known_hosts

  script:
    - |
      ssh -i ~/.ssh/id_deploy -p "$SSH_LAZAREFORTUNE_PORT" "$SSH_LAZAREFORTUNE_USER@$SSH_LAZAREFORTUNE_HOST" \
        "sudo -n -u fortune /usr/local/sbin/deploy-lazarefortune"

  only:
    - main
