services:
  app:
    container_name: app-lazarefortune
    restart: unless-stopped
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:80"
      - "8080:8080"
    volumes:
      - ".:/var/www/html"
    environment:
      DATABASE_URL: mysql://${DB_USER}:${DB_PASSWORD}@mariadb:3306/${DB_NAME}?serverVersion=10.5&charset=utf8mb4
      MAILER_DSN: smtp://mailhog:1025?transport=sync
    command: bash -c "pnpm run dev-server & apache2-foreground"
    depends_on:
      - database

  database:
    image: mariadb:10.5
    container_name: mariadb
    environment:
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
    volumes:
      - db_data:/var/lib/mysql
    ports:
      - "3307:3306"

  phpmyadmin:
    image: phpmyadmin:5.2
    container_name: phpmyadmin
    restart: always
    environment:
      PMA_HOST: database
      PMA_PORT: 3306
    ports:
      - "8081:80"
    depends_on:
      - database

  mailhog:
    image: mailhog/mailhog:v1.0.1
    ports:
      - "8025:8025"
      - "1025:1025"

  redis:
    image: redis:alpine
    container_name: redis
    restart: unless-stopped
    ports:
      - "6379:6379"

volumes:
  db_data: {}

