imports:
    - { resource: parameters.yaml }

services:
    _defaults:
        autowire: true
        autoconfigure: true

    App\:
        resource: '../src/'
        exclude:
            - '../src/Kernel.php'

    App\Shared\Twig\LucideIconExtension:
        arguments:
            $projectDir: '%kernel.project_dir%'
